### ISSUE TITLE
Bug with Facebooks Messaging

### ISSUE THREAD

**Issue by hefekranz** [NiklasGollenstede/stop-fingerprinting#4]
Hey Niklas! When on facebook, the entire message functionality was blocked by the addon. After I whitelisted facebook.com/messages/* it worked again. Sadly I didn't find any console output at about:debugging or in the dev console. So I can't give you more then the Firefox version, 49.0.2
Cheers!

**Comment by NiklasGollenstede** [comment]
Thanks for reporting this. But if whitelisting `facebook.com/messages/*` fixes this I don't see it as a higher priority and won't send time on fixing it in this version.
I hope to release a major update in about three month. Let's see if this ... bug also happens with that version.
