### ISSUE TITLE
WebExtensions port

### ISSUE THREAD

**Issue by gsantner** [NiklasGollenstede/stop-fingerprinting#9]
Hi there,
ist there a plan for this to be ported to WebExtensions? / if even possible fromAPI point of view

**Comment by NiklasGollenstede** [comment]
I actually started a port 18 month ago (55465a4) and put a few hundred hours of work into it. While I have learned a lot during that time, the unfortunate result, which became part of my bachelor theses, was that there are so many conceptual problems with the WebExtension framework when it comes to this kind of extensions, that it is not worth to bother.

If you care about fingerprinting resistance, you just have to use a browser that is build with that in mind (the Tor-Browser being the most prominent example). I'm pretty sure that if I'd take a detailed look at something like the canvas blocker, I'd find a critical issue that effectively renders it useless.

I should probably not the end of support for this extension on AMO.

**Comment by gsantner** [comment]
Nice to hear!

Is this thesis public available / open for read?

I finished mine too, with main topic open source, if you want to have a read :) <http://gsantner.net/#ba_thesis>

**Comment by NiklasGollenstede** [comment]
I haven't published it, but if you want, you can use this link to download it now: https://files.gollos.top/f/cb6f6c624d/?raw=1

It's German, but It seems you can read that :)

**Comment by gsantner** [comment]
nice 👍 thx
